---
- name: Install MicroK8S
  hosts: controlplane, worker
  gather_facts: true
  become: true
  tasks:
    - name: Install Microk8s
      shell: |
          sudo snap install microk8s --classic --channel=1.27
          microk8s status --wait-ready
          microk8s kubectl get nodes

    - name: Configure User
      shell: |
          sudo usermod -a -G microk8s $USER
          sudo chown -f -R $USER ~/.kube
          sudo su - $USER
          cat <<EOT >> ~/.bash_aliases
          alias kubectl='microk8s kubectl'
          EOT
          source ~/.bash_aliases

    - name: Get KubeConfig
      local_action: copy content="microk8s config" dest="~/.kube/microk8s_config_$HOSTNAME" mode=0777

# - name: Install controlplane components
#   hosts: controlplane
#   gather_facts: true
#   become: true
#   tasks:
#     - name: Enable Microk8s addons
#       shell: microk8s enable hostpath-storage ingress metrics-server host-access:ip=10.0.1.1 cert-manager

#     - name: Print join command
#       shell: microk8s add-node --format short | awk 'FNR <= 1'
#       register: kubernetes_join_command

#     - name: Copy join command to local file.
#       local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777

# - name: Install Kubeadm
#   hosts: worker
#   gather_facts: true
#   become: true
#   tasks:
#     - name: Copy join command from Ansiblehost to the worker nodes.
#       copy:
#         src: /tmp/kubernetes_join_command
#         dest: /tmp/kubernetes_join_command
#         mode: 0777
        
#     - name: Execute worker join command
#       shell: sh /tmp/kubernetes_join_command